version: '3'

services:
  nginx:
    image: detectiverust93/nginx:prod
    container_name: nginx
    restart: always
    depends_on:
      - node
    ports:
      - "80:80"
    networks:
      - mynetwork
  node:
    image: detectiverust93/node:prod
    container_name: node
    restart: always
    depends_on:
      - mysql
    networks:
      - mynetwork
  mysql:
    image: detectiverust93/mysql:prod
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
