version: '3'

services:
  nginx:
    image: detectiverust93/nginx:dev
    container_name: nginx
    restart: always
    depends_on:
      - node
    ports:
      - "8080:80"
    networks:
      - mynetwork
  node:
    image: detectiverust93/node:dev
    container_name: node
    restart: always
    depends_on:
      - mysql
    networks:
      - mynetwork
  mysql:
    image: detectiverust93/mysql:dev
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql

networks:
  mynetwork:
    driver: bridge
