version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    depends_on:
      - node
    ports:
      - "8080:80"
    networks:
      - mynetwork
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node
    restart: always
    depends_on:
      - mysql
    networks:
      - mynetwork
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    networks:
      - mynetwork
#    volumes:
#      - ./mysql/mysql_data:/var/lib/mysql

networks:
  mynetwork:
    driver: bridge
