version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    depends_on:
      - node
    ports:
      - "8080:80"
    networks:
      - mynetwork
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    entrypoint: ["sh", "-c", "npm install && dockerize -wait tcp://mysql:3306 -timeout 20s && node server.js"]
    container_name: node
    restart: always
    depends_on:
      - mysql
    networks:
      - mynetwork
    volumes:
      - ./node:/usr/src/app
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
